export const FETCH_TEACHERS_REQUEST = "FETCH_TEACHERS_REQUEST";
export const FETCH_TEACHERS_FAILED = "FETCH_TEACHERS_FAILED";
export const FETCH_TEACHERS_SUCCESS = "FETCH_TEACHERS_SUCCESS";
export const FETCH_BACKLOGS_REQUEST = "FETCH_BACKLOGS_REQUEST";
export const FETCH_BACKLOGS_FAILED = "FETCH_BACKLOGS_FAILED";
export const FETCH_BACKLOGS_SUCCESS = "FETCH_BACKLOGS_SUCCESS";
export const MACHINE_SET_CURRENT_TIME_REQUEST =
  "MACHINE_SET_CURRENT_TIME_REQUEST";
export const MACHINE_SET_CURRENT_TIME_SUCCESS =
  "MACHINE_SET_CURRENT_TIME_SUCCESS";
export const MACHINE_SET_CURRENT_TIME_FAILED =
  "MACHINE_SET_CURRENT_TIME_FAILED";
export const MACHINE_GET_ALL_USERS_REQUEST = "MACHINE_GET_ALL_USERS_REQUEST";
export const MACHINE_GET_ALL_USERS_SUCCESS = "MACHINE_GET_ALL_USERS_SUCCESS";
export const MACHINE_GET_ALL_USERS_FAILED = "MACHINE_GET_ALL_USERS_FAILED";
export const MACHINE_ADD_OR_UPDATE_TEACHER_REQUEST =
  "MACHINE_ADD_OR_UPDATE_TEACHER_REQUEST";
export const MACHINE_ADD_OR_UPDATE_TEACHER_SUCCESS =
  "MACHINE_ADD_OR_UPDATE_TEACHER_SUCCESS";
export const MACHINE_ADD_OR_UPDATE_TEACHER_FAILED =
  "MACHINE_ADD_OR_UPDATE_TEACHER_FAILED";
export const MACHINE_DELETE_TEACHER_REQUEST = "MACHINE_DELETE_TEACHER_REQUEST";
export const MACHINE_DELETE_TEACHER_SUCCESS = "MACHINE_DELETE_TEACHER_SUCCESS";
export const MACHINE_DELETE_TEACHER_FAILED = "MACHINE_DELETE_TEACHER_FAILED";
export const MACHINE_DELETE_ALL_ATTENDANCES_REQUEST =
  "MACHINE_DELETE_ALL_ATTENDANCES_REQUEST";
export const MACHINE_DELETE_ALL_ATTENDANCES_SUCCESS =
  "MACHINE_DELETE_ALL_ATTENDANCES_SUCCESS";
export const MACHINE_DELETE_ALL_ATTENDANCES_FAILED =
  "MACHINE_DELETE_ALL_ATTENDANCES_FAILED";
export const FETCH_TEACHER_DETAIL_REQUEST = "FETCH_TEACHER_DETAIL_REQUEST";
export const FETCH_TEACHER_DETAIL_SUCCESS = "FETCH_TEACHER_DETAIL_SUCCESS";
export const FETCH_TEACHER_DETAIL_ERROR = "FETCH_TEACHER_DETAIL_ERROR";
